const http=require('http');const fs=require('fs');const path=require('path');const {DatabaseSync}=require('node:sqlite');
const root=__dirname,dbDir=path.join(root,'.data');fs.mkdirSync(dbDir,{recursive:true});const db=new DatabaseSync(path.join(dbDir,'estudai.db'));
db.exec(`PRAGMA journal_mode=WAL; CREATE TABLE IF NOT EXISTS content(id INTEGER PRIMARY KEY,subject TEXT,level TEXT,title TEXT,body TEXT);CREATE TABLE IF NOT EXISTS sessions(id INTEGER PRIMARY KEY,subject TEXT,score INTEGER,total INTEGER,minutes INTEGER,year INTEGER,day INTEGER,answers TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP);CREATE TABLE IF NOT EXISTS mistakes(id INTEGER PRIMARY KEY,subject TEXT,topic TEXT,question TEXT,answer TEXT,correct TEXT,kind TEXT,review_at TEXT,resolved INTEGER DEFAULT 0);CREATE TABLE IF NOT EXISTS questions(id INTEGER PRIMARY KEY,year INTEGER,qindex INTEGER,language TEXT,discipline TEXT,title TEXT,context TEXT,introduction TEXT,files TEXT,alternatives TEXT,correct TEXT,UNIQUE(year,qindex,language));`);
if(!db.prepare('SELECT count(*) n FROM content').get().n){const add=db.prepare('INSERT INTO content(subject,level,title,body) VALUES(?,?,?,?)');[['matematica','fundamental','Razão e proporção','Entenda relações entre grandezas antes de avançar para questões contextualizadas.'],['portugues','fundamental','Leitura ativa','Identifique tema, finalidade, opinião e evidências em cada texto.'],['redacao','basico','Tese e projeto de texto','Construa uma posição clara e dois argumentos que serão desenvolvidos.'],['biologia','fundamental','Ecologia essencial','Revise cadeias alimentares, ciclos e relações ecológicas.']].forEach(x=>add.run(...x))}
function seedQuestions(){if(db.prepare('SELECT count(*) n FROM questions').get().n>=700)return;const insert=db.prepare(`INSERT OR IGNORE INTO questions(year,qindex,language,discipline,title,context,introduction,files,alternatives,correct) VALUES(?,?,?,?,?,?,?,?,?,?)`);db.exec('BEGIN');try{for(const year of [2020,2021,2022,2023]){const file=path.join(root,'dados','questoes',`${year}.json`);if(!fs.existsSync(file))continue;for(const q of JSON.parse(fs.readFileSync(file))){insert.run(year,q.index,q.language||'',q.discipline,q.title,q.context||'',q.alternativesIntroduction||'',JSON.stringify(q.files||[]),JSON.stringify(q.alternatives||[]),q.correctAlternative)}}db.exec('COMMIT')}catch(e){db.exec('ROLLBACK');console.error('Falha ao importar questões',e)}}seedQuestions();
const send=(res,code,data,type='application/json; charset=utf-8')=>{res.writeHead(code,{'Content-Type':type,'Access-Control-Allow-Origin':'*','Cache-Control':type.startsWith('application/json')?'no-store':'public, max-age=300'});res.end(type.startsWith('application/json')?JSON.stringify(data):data)};
const readBody=req=>new Promise((ok,no)=>{let b='';req.on('data',x=>b+=x);req.on('end',()=>{try{ok(JSON.parse(b||'{}'))}catch(e){no(e)}})});
const server=http.createServer(async(req,res)=>{const u=new URL(req.url,'http://localhost');
 if(u.pathname==='/api/health')return send(res,200,{ok:true,database:'sqlite',questions:db.prepare('SELECT count(*) n FROM questions').get().n});
 if(u.pathname==='/api/content')return send(res,200,db.prepare('SELECT * FROM content WHERE (? IS NULL OR subject=?)').all(u.searchParams.get('subject'),u.searchParams.get('subject')));
 if(u.pathname==='/api/questions'){const year=+(u.searchParams.get('year')||2023),day=+(u.searchParams.get('day')||1),limit=Math.min(90,Math.max(1,+(u.searchParams.get('limit')||10))),language=u.searchParams.get('language')||'ingles';const min=day===1?1:91,max=day===1?90:180;let rows=db.prepare(`SELECT * FROM questions WHERE year=? AND qindex BETWEEN ? AND ? AND (qindex>5 OR language=? OR language='') ORDER BY qindex LIMIT ?`).all(year,min,max,language,limit);rows=rows.map(q=>({...q,files:JSON.parse(q.files),alternatives:JSON.parse(q.alternatives)}));return send(res,200,{year,day,total:rows.length,questions:rows})}
 if(u.pathname==='/api/progress')return send(res,200,db.prepare('SELECT subject,count(*) sessions,avg(score*100.0/total) accuracy,sum(minutes) minutes FROM sessions GROUP BY subject').all());
 if(req.method==='POST'&&u.pathname==='/api/sessions'){try{const x=await readBody(req);const r=db.prepare('INSERT INTO sessions(subject,score,total,minutes,year,day,answers) VALUES(?,?,?,?,?,?,?)').run(x.subject||'geral',x.score,x.total,x.minutes||0,x.year||null,x.day||null,JSON.stringify(x.answers||{}));return send(res,201,{id:Number(r.lastInsertRowid)})}catch(e){return send(res,400,{error:'Dados inválidos'})}}
 let file=u.pathname==='/'?'index.html':decodeURIComponent(u.pathname.slice(1));file=path.normalize(file);if(file.startsWith('..'))return send(res,403,'Proibido','text/plain');const target=path.join(root,file);fs.readFile(target,(e,data)=>{if(e)return send(res,404,'Não encontrado','text/plain');const ext=path.extname(target);send(res,200,data,{'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.json':'application/json; charset=utf-8'}[ext]||'application/octet-stream')})});
const port=process.env.PORT||4173;server.listen(port,'0.0.0.0',()=>console.log(`Estudaí: ${db.prepare('SELECT count(*) n FROM questions').get().n} questões em http://0.0.0.0:${port}`));
