const http=require('http');const fs=require('fs');const path=require('path');const crypto=require('crypto');
const root=__dirname,SUPABASE_URL=(process.env.SUPABASE_URL||'').replace(/\/$/,''),SUPABASE_KEY=process.env.SUPABASE_SERVICE_ROLE_KEY||'',cloudReady=!!(SUPABASE_URL&&SUPABASE_KEY);
const courses=[
['matematica','Matemática','Formação escolar','Fundamental ao avançado','Álgebra, geometria, estatística e resolução de problemas.','π','#e3f5ee'],['portugues','Português e Literatura','Formação escolar','Fundamental ao avançado','Gramática, interpretação, escrita e literatura.','Aa','#eee9ff'],['ciencias-natureza','Ciências da Natureza','Formação escolar','Fundamental ao avançado','Biologia, química e física em trilhas conectadas.','⚗','#e5f5e9'],['humanas','Ciências Humanas','Formação escolar','Fundamental ao avançado','História, geografia, filosofia e sociologia.','◎','#fff0dd'],['redacao','Produção de Texto','Comunicação','Básico ao avançado','Argumentação, estrutura, estilo e revisão.','✎','#f0eaff'],['ingles','Inglês','Idiomas','Iniciante ao avançado','Vocabulário, leitura, escuta, escrita e conversação.','EN','#ffe9e5'],['espanhol','Espanhol','Idiomas','Iniciante ao avançado','Compreensão e comunicação para situações reais.','ES','#fff0e5'],['javascript','JavaScript','Programação','Iniciante ao avançado','Lógica, web, APIs, Node.js e projetos.','JS','#fff3be'],['python','Python','Programação','Iniciante ao avançado','Fundamentos, automação, dados e aplicações.','Py','#dfefff'],['html-css','HTML e CSS','Programação','Iniciante ao avançado','Sites responsivos, acessíveis e profissionais.','</>','#ffe5eb'],['java','Java','Programação','Iniciante ao avançado','Orientação a objetos, aplicações e APIs.','Jv','#ffe8df'],['sql','SQL e Banco de Dados','Programação','Iniciante ao avançado','Modelagem, consultas e bancos relacionais.','DB','#e3f4f0'],['git','Git e GitHub','Ferramentas','Iniciante ao intermediário','Versionamento, colaboração e portfólio.','Git','#fce8e4']].map(x=>({id:x[0],title:x[1],category:x[2],level:x[3],description:x[4],icon:x[5],color:x[6],published:true}));
const modules=['Fundamentos','Prática guiada','Projeto ou desafio'].map((title,i)=>({id:i+1,title,position:i+1,content:['Construa a base necessária para avançar com segurança.','Aplique o conhecimento com exercícios e feedback.','Demonstre domínio em uma atividade prática.'][i]}));
const plans=[{id:'explorar',name:'Explorar',price_cents:0,description:'Comece sem compromisso.',features:['Acesso a aulas introdutórias','Diagnóstico de nível','Progresso básico'],highlighted:false},{id:'essencial',name:'Essencial',price_cents:2990,description:'Para criar uma rotina sólida.',features:['Todos os cursos essenciais','Exercícios e revisões','Plano semanal personalizado','30 dias grátis'],highlighted:false},{id:'pro',name:'Pro',price_cents:5990,description:'Para evoluir mais rápido.',features:['Tudo do Essencial','Programação completa','Projetos práticos','Relatórios avançados','30 dias grátis'],highlighted:true},{id:'familia',name:'Família',price_cents:8990,description:'Aprendizado para até 4 pessoas.',features:['Tudo do Pro','Até 4 perfis','Painel familiar','Trilhas individuais','30 dias grátis'],highlighted:false}];
const send=(res,code,data,type='application/json; charset=utf-8')=>{res.writeHead(code,{'Content-Type':type,'Access-Control-Allow-Origin':'*','Cache-Control':type.startsWith('application/json')?'no-store':'public, max-age=300'});res.end(type.startsWith('application/json')?JSON.stringify(data):data)};const body=req=>new Promise((ok,no)=>{let b='';req.on('data',x=>b+=x);req.on('end',()=>{try{ok(JSON.parse(b||'{}'))}catch(e){no(e)}})});
async function supabase(table,{method='GET',query='',data,prefer='return=representation'}={}){if(!cloudReady)throw new Error('CLOUD_NOT_CONFIGURED');const r=await fetch(`${SUPABASE_URL}/rest/v1/${table}${query}`,{method,headers:{apikey:SUPABASE_KEY,Authorization:`Bearer ${SUPABASE_KEY}`,'Content-Type':'application/json',Prefer:prefer},body:data?JSON.stringify(data):undefined});const text=await r.text();if(!r.ok)throw new Error(`Supabase ${r.status}: ${text}`);return text?JSON.parse(text):null}
const server=http.createServer(async(req,res)=>{const u=new URL(req.url,'http://localhost');
 if(u.pathname==='/api/health')return send(res,200,{ok:true,product:'Estudaí',storage:'supabase',cloudConfigured:cloudReady,courses:courses.length});
 if(u.pathname==='/api/courses'){const category=u.searchParams.get('category');return send(res,200,courses.filter(c=>!category||c.category===category))}
 if(u.pathname.startsWith('/api/courses/')){const course=courses.find(c=>c.id===u.pathname.split('/').pop());return course?send(res,200,{...course,modules}):send(res,404,{error:'Curso não encontrado'})}
 if(u.pathname==='/api/plans')return send(res,200,plans);
 if(req.method==='POST'&&u.pathname==='/api/trials'){try{const x=await body(req),email=(x.email||'').trim().toLowerCase(),name=(x.name||'').trim();if(name.length<2)return send(res,400,{error:'Informe seu nome.'});if(!/^\S+@\S+\.\S+$/.test(email))return send(res,400,{error:'Informe um e-mail válido.'});if(!x.ageConfirmed||!x.consent)return send(res,400,{error:'Confirme a autorização de idade e aceite os documentos.'});if(!cloudReady)return send(res,503,{error:'O banco Supabase ainda não foi conectado. O pré-cadastro não foi salvo localmente.'});const existing=await supabase('trials',{query:`?email=eq.${encodeURIComponent(email)}&select=id,expires_at`});if(existing.length)return send(res,200,{ok:true,alreadyRegistered:true,expiresAt:existing[0].expires_at,message:'Este e-mail já está no pré-cadastro na nuvem.'});const now=new Date(),end=new Date(now.getTime()+30*864e5),id=crypto.randomUUID(),version=x.privacyVersion||'2026-10-05';await supabase('trials',{method:'POST',data:{id,email,name,plan_id:x.planId||'pro',status:'pre_registered',started_at:now.toISOString(),expires_at:end.toISOString(),privacy_version:version,age_confirmed:true}});await supabase('consents',{method:'POST',data:[{trial_id:id,kind:'terms',version,granted:true},{trial_id:id,kind:'privacy',version,granted:true}]});return send(res,201,{ok:true,trialDays:30,expiresAt:end.toISOString(),message:'Pré-cadastro salvo com segurança na nuvem.'})}catch(e){console.error(e.message);return send(res,502,{error:'Não foi possível salvar no banco em nuvem.'})}}
 if(u.pathname==='/api/progress'){if(!cloudReady)return send(res,200,[]);try{return send(res,200,await supabase('study_sessions',{query:'?select=*'}))}catch{return send(res,502,{error:'Falha ao consultar progresso'})}}
 let file=u.pathname==='/'?'index.html':decodeURIComponent(u.pathname.slice(1));file=path.normalize(file);if(file.startsWith('..'))return send(res,403,'Proibido','text/plain');fs.readFile(path.join(root,file),(e,data)=>{if(e)return send(res,404,'Não encontrado','text/plain');const ext=path.extname(file);send(res,200,data,{'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.json':'application/json; charset=utf-8'}[ext]||'application/octet-stream')})});
const port=process.env.PORT||4173;server.listen(port,'0.0.0.0',()=>console.log(`Estudaí: Supabase ${cloudReady?'conectado':'aguardando configuração'} em http://0.0.0.0:${port}`));
